module "cart" {
  source = "./vendor/modules/app"
  ENV = var.ENV
  INSTANCE_TYPE = var.INSTANCE_TYPE
  SPOT_INSTANCE_COUNT = var.SPOT_INSTANCE_COUNT
  COMPONENT = var.COMPONENT
  OD_INSTANCE_COUNT = var.OD_INSTANCE_COUNT
  APP_PORT = var.APP_PORT
  WORKSTATION_IP = var.WORKSTATION_IP
//  DOCTDB_PORT = var.DOCTDB_PORT
//  DOCDB_INSTANCE_CLASS = var.DOCDB_INSTANCE_CLASS
//  DOCDB_INSTANCE_COUNT = var.DOCDB_INSTANCE_COUNT
}